//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricityMetering.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectricityMetering.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BalanceRadioButton.
        /// </summary>
        internal static string BalanceRadioButton {
            get {
                return ResourceManager.GetString("BalanceRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BigTableBorder.
        /// </summary>
        internal static string BigTableBorder {
            get {
                return ResourceManager.GetString("BigTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BigTableCellText.
        /// </summary>
        internal static string BigTableCellText {
            get {
                return ResourceManager.GetString("BigTableCellText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BigTableCellTextReadonly.
        /// </summary>
        internal static string BigTableCellTextReadonly {
            get {
                return ResourceManager.GetString("BigTableCellTextReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верный пароль.
        /// </summary>
        internal static string CorrectPassword {
            get {
                return ResourceManager.GetString("CorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электрик.
        /// </summary>
        internal static string Electrician {
            get {
                return ResourceManager.GetString("Electrician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IndicationsRadioButton.
        /// </summary>
        internal static string IndicationsRadioButton {
            get {
                return ResourceManager.GetString("IndicationsRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InfoRadioButton.
        /// </summary>
        internal static string InfoRadioButton {
            get {
                return ResourceManager.GetString("InfoRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LittleTableBorder.
        /// </summary>
        internal static string LittleTableBorder {
            get {
                return ResourceManager.GetString("LittleTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LittleTableCellTextReadonly.
        /// </summary>
        internal static string LittleTableCellTextReadonly {
            get {
                return ResourceManager.GetString("LittleTableCellTextReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PaymentRadioButton.
        /// </summary>
        internal static string PaymentRadioButton {
            get {
                return ResourceManager.GetString("PaymentRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Председатель.
        /// </summary>
        internal static string President {
            get {
                return ResourceManager.GetString("President", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TariffRadioButton.
        /// </summary>
        internal static string TariffRadioButton {
            get {
                return ResourceManager.GetString("TariffRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный пароль.
        /// </summary>
        internal static string UncorrectPassord {
            get {
                return ResourceManager.GetString("UncorrectPassord", resourceCulture);
            }
        }
    }
}
